package db

import (
	"context"
	"log"
	"os"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
	// Import for loading environment variables
)

// Queries is the struct generated by sqlc
var testQueries *Queries

const (
	dbDriver = "postgres"
	DBSource = "postgresql://bank_app_user:@BankApp123@localhost:5432/bank_app_database?sslmode=disable"
)

func TestMain(m *testing.M) {

	// Create a new pgx connection pool
	connPool, err := pgxpool.New(context.Background(), DBSource)
	if err != nil {
		log.Fatal("cannot connect to db:", err)
	}

	// Ensure the connection pool is closed after tests
	defer connPool.Close()

	// Create a Queries instance using the pgx connection pool
	testQueries = New(connPool)

	// Run the tests
	os.Exit(m.Run())
}
